set(DPDK_ROOT "${PROJECT_SOURCE_DIR}/build/dependencies/dpdk-25.11.2/install" CACHE PATH "DPDK installation prefix")

set(OLD_PKG_CONFIG_PATH "$ENV{PKG_CONFIG_PATH}")
set(OLD_PKG_CONFIG_LIBDIR "$ENV{PKG_CONFIG_LIBDIR}")

set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_LIBDIR} "${DPDK_ROOT}/lib/pkgconfig")

find_package(PkgConfig REQUIRED)
pkg_check_modules(DPDK REQUIRED "libdpdk=25.11.2")

set(ENV{PKG_CONFIG_PATH} "${OLD_PKG_CONFIG_PATH}")
set(ENV{PKG_CONFIG_LIBDIR} "${OLD_PKG_CONFIG_LIBDIR}")

add_library(DPDK::DPDK INTERFACE IMPORTED)

set_target_properties(DPDK::DPDK PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${DPDK_STATIC_INCLUDE_DIRS}"
        INTERFACE_COMPILE_OPTIONS     "${DPDK_STATIC_CFLAGS_OTHER}"
        INTERFACE_LINK_LIBRARIES      "${DPDK_STATIC_LDFLAGS}"
)